# KabuKids.kv
#:include screens/splash.kv
#:include screens/login.kv
#:include screens/make_account.kv
#:include screens/dashboard.kv
#:include screens/profile.kv
#:include screens/report.kv
#:include screens/transcript.kv

#:include screens/portionSizeBefore.kv
#:include screens/portionSizeAfter.kv
#:include screens/inputIngredientsBM.kv
#:include screens/inputIngredientsAM.kv
#:include screens/editProfile.kv
#:include screens/session.kv

WindowManager:
    SplashScreen:
    LoginPage:
    MakeAccountPage:
    DashboardPage:
    ProfilePage:
    ReportPage:
    TranscriptPage:

    PortionSizeBeforePage:
    PortionSizeAfterPage:
    InputIngredientsBMPage:
    InputIngredientsAMPage:
    EditProfilePage:
    SessionPage: