# KabuKids.kv
#:include screens/splash.kv
#:include screens/login.kv
#:include screens/make_account.kv
#:include screens/dashboard.kv
#:include screens/camera.kv
#:include screens/profile.kv
#:include screens/report.kv
#:include screens/transcript.kv
#:include screens/suggestions.kv

WindowManager:
    SplashScreen:
    LoginPage:
    MakeAccountPage:
    DashboardPage:
    CameraPage:
    ProfilePage:
    ReportPage:
    TranscriptPage:
    SuggestionsPage: