#:import secondary_color colors.SECONDARY_COLOR
#:import accent_color colors.ACCENT_COLOR
#:import primary_color colors.PRIMARY_COLOR
#:import dark_color colors.DARK_COLOR
#:import light_color colors.LIGHT_COLOR
#:import dp kivy.metrics.dp

<DashboardPage>:
    name: "dashboard"

    canvas.before:
        Color:
            rgba: primary_color
        Rectangle:
            pos: self.pos
            size: self.size

    BoxLayout:
        orientation: 'vertical'
        
        # Header
        BoxLayout:
            size_hint_y: None
            height: dp(60)
            padding: dp(10)
            spacing: dp(10)
            
            # Left side: Profile picture and info
            BoxLayout:
                orientation: 'horizontal'
                spacing: dp(10)
                
                Image:
                    source: "screens/icons/dashboard.png" 
                    size_hint: None, None
                    size: 50, 50
                    pos_hint: {"center_x": 0.50, "center_y": 0.5}
                    allow_stretch: True
                    keep_ratio: True
                
                # Name
                BoxLayout:
                    orientation: 'vertical'
                    Label:
                        text: root.user_name
                        font_name: "screens/fonts/Valekon.otf"
                        font_size: 30
                        halign: 'left'
                        valign: 'middle'
                        size_hint_y: None
                        color: secondary_color
                        height: self.texture_size[1]
            
            # Right side: Edit button
            ImageButton:
                source: "screens/icons/profile.png"
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                on_press: app.root.current = "profile"

        # ====== DIVIDER LINE ======
        Widget:
            size_hint_y: None
            height: dp(2)
            canvas:
                Color:
                    rgba: secondary_color
                Rectangle:
                    pos: self.pos
                    size: self.width, dp(2)
        
        # Main content area
        ScrollView:
            BoxLayout:
                orientation: 'vertical'
                padding: dp(20)
                spacing: dp(20)
                size_hint_y: None
                height: self.minimum_height
                
                # START MEAL button
                Button:
                    text: "START MEAL"
                    size_hint_y: None
                    height: dp(60)
                    size_hint_x: 0.99
                    pos_hint: {'center_x': 0.5}
                    background_normal: ''        # use custom canvas instead of default bg
                    background_color: 0,0,0,0
                    on_press: app.root.current = "inputIngredientsBM"
                    font_size: sp(18)
                    bold: True
                    color: 1,1,1,1
                    canvas.before:
                        Color:
                            rgba: light_color
                        RoundedRectangle:
                            pos: self.pos
                            size: self.size
                            radius: [dp(12), dp(12), dp(12), dp(12)]
                
                # PREVIOUS MEALS section
                Label:
                    text: "PREVIOUS MEALS"
                    font_name: "screens/fonts/Valekon.otf"
                    color: secondary_color
                    font_size: 30
                    size_hint_y: None
                    height: self.texture_size[1]
                    halign: 'left'
                    text_size: self.size
                
                # Container for dynamic meal items
                BoxLayout:
                    id: meals_list  # key
                    orientation: 'vertical'
                    spacing: dp(10)
                    size_hint_y: None
                    height: self.minimum_height

<ImageButton@ButtonBehavior+Image>:
    allow_stretch: True
    keep_ratio: True
    size_hint: None, None
    size: dp(50), dp(50)