#:import secondary_color colors.SECONDARY_COLOR
#:import accent_color colors.ACCENT_COLOR
#:import primary_color colors.PRIMARY_COLOR
#:import dark_color colors.DARK_COLOR
#:import light_color colors.LIGHT_COLOR
#:import super_light colors.SUPER_LIGHT
#:import dp kivy.metrics.dp


<ReportPage>:
    name: "report"
    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    ScrollView:
        BoxLayout:
            orientation: 'vertical'
            size_hint_y: None
            height: self.minimum_height
            padding: [20, 20]
            spacing: 15

            # --- Top: REPORT + Back Button ---
            BoxLayout:
                size_hint_y: None
                height: 60
                spacing: 10

                Label:
                    text: "REPORT"
                    font_name: "screens/fonts/Valekon.otf"
                    color: secondary_color
                    font_size: 35
                    bold: True
                    halign: 'left'
                    valign: 'middle'
                    text_size: self.size

                ImageButton:
                    source: "screens/icons/dashboard.png"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    on_press: app.root.current = "dashboard"

            # --- Date & Time ---
            Label:
                text: root.date
                color: light_color
                font_size: '16sp'
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            Label:
                text: root.time_range
                color: light_color
                font_size: '16sp'
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            # --- Divider ---
            Widget:
                size_hint_y: None
                height: 2
                canvas:
                    Color: 
                        rgba: secondary_color
                    Rectangle:
                        pos: (self.parent.x + self.parent.width * 0.005, self.y)
                        size: (self.parent.width * 0.99, 2)

            # --- SUMMARY Header ---
            Label:
                text: "SUMMARY"
                color: secondary_color
                font_name: "screens/fonts/Valekon.otf"
                font_size: 28
                bold: True
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            # --- SUMMARY Content ---
            Label:
                text: root.summary_text
                color: light_color
                font_size: '16sp'
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            # --- Divider ---
            Widget:
                size_hint_y: None
                height: 2
                canvas:
                    Color:
                        rgba: secondary_color
                    Rectangle:
                        pos: (self.parent.x + self.parent.width * 0.005, self.y)
                        size: (self.parent.width * 0.99, 2)

            # --- FOOD BEFORE MEAL ---
            Label:
                text: "FOOD BEFORE MEAL"
                font_size: 28
                font_name: "screens/fonts/Valekon.otf"
                color: secondary_color
                bold: True
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            Label:
                text: root.food_before_text
                font_size: 20
                color: light_color
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            # --- FOOD NOT FINISHED ---
            Label:
                text: "FOOD NOT FINISHED"
                font_name: "screens/fonts/Valekon.otf"
                color: secondary_color
                font_size: 28
                bold: True
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            Label:
                text: root.food_not_finished_text
                color: light_color
                font_size: 20
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            # --- Portion Images ---
            #Label:
            #    text: "PORTION IMAGES"
            #    font_size: '22sp'
            #    bold: True
            #    halign: 'left'
            #    valign: 'top'
            #    text_size: self.width, None
            #    size_hint_y: None
            #    height: self.texture_size[1]

            #BoxLayout:
            #    orientation: 'horizontal'
            #    size_hint_y: None
            #    height: 200
            #    spacing: 10

            #    Image:
            #        source: root.portion_before_source
            #        fit_mode: "contain"
            #        allow_stretch: True

            #    Image:
            #        source: root.portion_after_source
            #        fit_mode: "contain"
            #        allow_stretch: True

            # --- Divider ---
            Widget:
                size_hint_y: None
                height: 2
                canvas:
                    Color:
                        rgba: secondary_color
                    Rectangle:
                        pos: (self.parent.x + self.parent.width * 0.005, self.y)
                        size: (self.parent.width * 0.99, 2)

            # --- INGREDIENT SUGGESTIONS Header ---
            Label:
                text: "INGREDIENT SUGGESTIONS"
                font_name: "screens/fonts/Valekon.otf"
                color: secondary_color
                font_size: 28
                bold: True
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            BoxLayout:
                size_hint_y: None
                height: self.minimum_height
                padding: [15, 15]
                canvas.before:
                    Color:
                        rgba: super_light
                    Line:
                        rectangle: (self.x, self.y, self.width, self.height)
                        width: 1.5

                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 12
                    Label:
                        text: root.formatted_ingredient_suggestions
                        color: light_color
                        font_size: 20
                        halign: 'left'
                        valign: 'top'
                        text_size: self.width - 30, None
                        size_hint_y: None
                        height: self.texture_size[1]

            # --- Divider ---
            Widget:
                size_hint_y: None
                height: 2
                canvas:
                    Color:
                        rgba:secondary_color
                    Rectangle:
                        pos: (self.parent.x + self.parent.width * 0.005, self.y)
                        size: (self.parent.width * 0.99, 2)

            # --- CONVERSATION SUGGESTIONS Header ---
            Label:
                text: "CONVERSATION SUGGESTIONS"
                font_size: 28
                font_name: "screens/fonts/Valekon.otf"
                color: secondary_color
                bold: True
                halign: 'left'
                valign: 'top'
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]

            BoxLayout:
                size_hint_y: None
                height: self.minimum_height
                padding: [15, 15]
                canvas.before:
                    Color:
                        rgba: super_light
                    Line:
                        rectangle: (self.x, self.y, self.width, self.height)
                        width: 1.5

                GridLayout:
                    cols: 1
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: 12
                    Label:
                        text: root.formatted_conversation_suggestions
                        font_size: 20
                        color: light_color
                        halign: 'left'
                        valign: 'top'
                        text_size: self.width - 30, None
                        size_hint_y: None
                        height: self.texture_size[1]

            # Spacer
            Widget:
                size_hint_y: None
                height: 20

            # --- TRANSCRIPT Button ---
            Button:
                text: "TRANSCRIPT"
                font_name: "screens/fonts/Valekon.otf"
                size_hint_y: None
                height: 60
                font_size: 35
                background_normal: ''
                background_color: accent_color
                color: primary_color
                on_press: app.root.current = "transcript"
                canvas.before:
                    Color:
                        rgba: accent_color
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [20,]

<ImageButton@ButtonBehavior+Image>:
    allow_stretch: True
    keep_ratio: True
    size_hint: None, None
    size: dp(50), dp(50)