#:import secondary_color colors.SECONDARY_COLOR

<SessionPage>:
    name: "session"
    canvas.before:
        Color:
            rgba: secondary_color
        Rectangle:
            pos: self.pos
            size: self.size

    FloatLayout:
        # Centered emotion video
        Video:
            id: emos_img
            source: ""    # will be set from Python
            allow_stretch: True
            keep_ratio: True
            size_hint: None, None
            size: dp(820), dp(820)
            pos_hint: {"center_x": 0.5, "center_y": 0.5}
            state: 'play'
            options: {'eos': 'loop'}

        # Small button in the top-right corner
        Button:
            text: "End Session"
            size_hint: None, None
            size: dp(140), dp(36)
            pos_hint: {"right": 0.98, "top": 0.95}
            background_color: 1, 0, 0, 1
            on_release: root.end_session()